version: '3.8'

services:
  tw-mrt:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: tw-mrt-glucose-prediction
    volumes:
      - ./data:/app/data
      - ./results:/app/results
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONPATH=/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: python main.py
    
  tensorboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tw-mrt-tensorboard
    ports:
      - "6006:6006"
    volumes:
      - ./logs:/app/logs
    command: tensorboard --logdir=/app/logs --host=0.0.0.0 --port=6006
    depends_on:
      - tw-mrt 